const mongoose = require('mongoose');

const UserSchema = new mongoose.Schema({
    firstName:{
        type:String,
        required:true,
        trim:true
    },
    lastName:{
        type:String,
        required:true,
        trim:true
    },
    email:{
        type:String,
        required:true,
        trim:true
    },
    password:{
        type:String,
        required:true, 
    },
    confirmPassword:{
        type:String,
        required:true, 
    },
    accountType:{
        type:String,
        enum:["Student","Teacher","Admin"],
        required:true
    },
    approved:{
        type:Boolean,
        default:true
    },
    active:{
        type:Boolean,
        default:true
    },
    additionalInfo:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Profile",
        required:true
    },
    courses:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Course"
    }],
    image:{
        type:String,
        required:true
    },
    token:{
        type:String
    },
    resetPasswordExpires:{
        type:Date
    },
    courseProgress:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"CourseProgress"
    }]

},{timestamps:true})
module.exports = mongoose.model('User',UserSchema)